import type { Page } from "@playwright/test";

/**
 * Installs a fake `window.__TAURI_INTERNALS__` before the app loads, so the
 * real frontend renders with deterministic data in a plain browser. Commands
 * mirror the fixtures used by the vitest suite (src/test/commands.ts).
 */
export async function mockTauri(page: Page, overrides: Record<string, unknown> = {}) {
  await page.addInitScript((ov: Record<string, unknown>) => {
    const SUMMARY = {
      balance: 842000,
      daily_budget: 4300,
      daily_ceiling_source: "chosen",
      ceiling_proposal_pending: false,
      daily_spend_today: 3800,
      card_spend_today_cents: 0,
      reserve_months: 4.5,
      reserve_state: "verdict",
      reserve_basis_months: 6,
      reserve_trend: "down",
      spending_mode: "debit",
      card_gate: "unknown",
      card_gate_economy: "unknown",
      card_gate_economy_bps: null,
      card_gate_reserve: "unknown",
      cartao_month_cents: 0,
      next_fatura_date: null,
      next_fatura_amount_cents: 0,
      upcoming_invoices: [],
      transaction_count: 42,
      last_real_tx_date: "2026-06-09",
    };

    const FORECAST = {
      today: "2026-06-10",
      horizon_end: "2026-06-30",
      safe_to_spend_today_cents: 35000,
      deepest_deficit: { date: "2026-06-15", balance_cents: 587700 },
      daily: [
        {
          date: "2026-06-10",
          income_cents: 0,
          fixed_out_cents: 0,
          daily_out_cents: 3800,
          balance_cents: 842000,
        },
        {
          date: "2026-06-11",
          income_cents: 0,
          fixed_out_cents: 0,
          daily_out_cents: 0,
          balance_cents: 842000,
        },
        {
          date: "2026-06-12",
          income_cents: 0,
          fixed_out_cents: 18900,
          daily_out_cents: 0,
          balance_cents: 823100,
        },
        {
          date: "2026-06-13",
          income_cents: 0,
          fixed_out_cents: 0,
          daily_out_cents: 0,
          balance_cents: 823100,
        },
        {
          date: "2026-06-14",
          income_cents: 0,
          fixed_out_cents: 0,
          daily_out_cents: 0,
          balance_cents: 823100,
        },
        {
          date: "2026-06-15",
          income_cents: 0,
          fixed_out_cents: 230000,
          daily_out_cents: 4300,
          balance_cents: 587700,
        },
        {
          date: "2026-06-16",
          income_cents: 0,
          fixed_out_cents: 0,
          daily_out_cents: 0,
          balance_cents: 587700,
        },
        {
          date: "2026-06-17",
          income_cents: 0,
          fixed_out_cents: 0,
          daily_out_cents: 0,
          balance_cents: 587700,
        },
        {
          date: "2026-06-18",
          income_cents: 0,
          fixed_out_cents: 0,
          daily_out_cents: 0,
          balance_cents: 587700,
        },
        {
          date: "2026-06-19",
          income_cents: 0,
          fixed_out_cents: 0,
          daily_out_cents: 0,
          balance_cents: 587700,
        },
        {
          date: "2026-06-20",
          income_cents: 0,
          fixed_out_cents: 12500,
          daily_out_cents: 0,
          balance_cents: 575200,
        },
        {
          date: "2026-06-21",
          income_cents: 0,
          fixed_out_cents: 0,
          daily_out_cents: 0,
          balance_cents: 575200,
        },
        {
          date: "2026-06-22",
          income_cents: 0,
          fixed_out_cents: 0,
          daily_out_cents: 0,
          balance_cents: 575200,
        },
        {
          date: "2026-06-23",
          income_cents: 0,
          fixed_out_cents: 0,
          daily_out_cents: 0,
          balance_cents: 575200,
        },
        {
          date: "2026-06-24",
          income_cents: 0,
          fixed_out_cents: 0,
          daily_out_cents: 0,
          balance_cents: 575200,
        },
        {
          date: "2026-06-25",
          income_cents: 700000,
          fixed_out_cents: 0,
          daily_out_cents: 0,
          balance_cents: 1275200,
        },
        {
          date: "2026-06-26",
          income_cents: 0,
          fixed_out_cents: 0,
          daily_out_cents: 0,
          balance_cents: 1275200,
        },
        {
          date: "2026-06-27",
          income_cents: 0,
          fixed_out_cents: 0,
          daily_out_cents: 0,
          balance_cents: 1275200,
        },
        {
          date: "2026-06-28",
          income_cents: 0,
          fixed_out_cents: 41200,
          daily_out_cents: 0,
          balance_cents: 1234000,
        },
        {
          date: "2026-06-29",
          income_cents: 0,
          fixed_out_cents: 0,
          daily_out_cents: 0,
          balance_cents: 1234000,
        },
        {
          date: "2026-06-30",
          income_cents: 0,
          fixed_out_cents: 0,
          daily_out_cents: 0,
          balance_cents: 1234000,
        },
      ],
      month_end: [{ year: 2026, month: 6, balance_cents: 1234000 }],
      months: [
        {
          year: 2026,
          month: 6,
          income_cents: 700000,
          performance_cents: 450000,
          cost_of_living_cents: 250000,
          fixed_out_cents: 250000,
          daily_out_cents: 0,
          cartao_cents: 0,
          savings_rate_bps: 2500,
          real_daily_avg_cents: 3000,
          economia_cents: 175000,
          patrimonio_cents: 0,
        },
        {
          year: 2026,
          month: 7,
          income_cents: 900000,
          performance_cents: 90000,
          cost_of_living_cents: 810000,
          fixed_out_cents: 810000,
          daily_out_cents: 0,
          cartao_cents: 0,
          savings_rate_bps: 1000,
          real_daily_avg_cents: 0,
          economia_cents: 0,
          patrimonio_cents: 0,
        },
      ],
      cash_headroom_cents: 587700,
      savings_headroom_cents: 35000,
      binding_guardrail: "cash",
      savings_target_bps: 2500,
      annual_savings: {
        realized_income_cents: 5000000,
        realized_savings_cents: 300000,
        registered_economia_cents: 250000,
        patrimonio_cents: 0,
        economia_ruler_cents: 250000,
        economia_ruler_rate_bps: 500,
        includes_previdencia: false,
        economia_state: "verdict",
        realized_rate_bps: 600,
        projected_income_cents: 6000000,
        projected_savings_cents: 1500000,
        projected_rate_bps: 2500,
        target_bps: 2500,
      },
      coverage: [
        {
          year: 2026,
          month: 8,
          projected_outflow_cents: 416500,
          baseline_outflow_cents: 1064900,
          coverage_bps: 3911,
          is_complete: false,
          estimated_missing_cents: 648400,
        },
      ],
      baseline_outflow_cents: 1064900,
      trusted_through_month: "2026-07",
      total_missing_cents: 648400,
    };

    const TXNS = [
      {
        id: "t1",
        type: "expense",
        amount: 4300,
        description: "Despesa demo variável",
        date: "2026-06-10",
        payment_method: "debit",
        is_projection: false,
        is_fixed: false,
        owners: ["Pessoa A", "Pessoa B"],
        tags: [],
        provenance: "importado",
        line_items: [],
        due_date: null,
        installment_index: null,
        installment_total: null,
        has_refund_link: false,
      },
      {
        id: "t2",
        type: "expense",
        amount: 18900,
        description: "Compromisso demo no crédito",
        date: "2026-06-08",
        payment_method: "credit",
        is_projection: false,
        is_fixed: false,
        owners: [],
        tags: [],
        provenance: "manual",
        line_items: [],
        due_date: null,
        installment_index: 3,
        installment_total: 12,
        has_refund_link: true,
      },
      {
        id: "t3",
        type: "expense",
        amount: 12500,
        description: "Compromisso fixo demo",
        date: "2026-06-05",
        payment_method: "pix",
        is_projection: false,
        is_fixed: true,
        owners: [],
        tags: [],
        provenance: "importado",
        line_items: [
          {
            id: "li-t3-card",
            transaction_id: "t3",
            amount_cents: 4500,
            description: "Compra credito demo",
            position: 0,
            kind: "cartao",
            section: "CARTÕES |",
          },
          {
            id: "li-t3-saida",
            transaction_id: "t3",
            amount_cents: 5500,
            description: "Conta fixa demo",
            position: 1,
            kind: "saida",
            section: "CONTAS:",
          },
        ],
        due_date: "2026-06-28",
        installment_index: null,
        installment_total: null,
        has_refund_link: false,
      },
      {
        id: "t4",
        type: "income",
        amount: 700000,
        description: "Receita demo projetada",
        date: "2026-06-25",
        payment_method: "",
        is_projection: true,
        is_fixed: false,
        owners: [],
        tags: [],
        provenance: "projetado",
        line_items: [],
        due_date: null,
        installment_index: null,
        installment_total: null,
        has_refund_link: false,
      },
      {
        id: "t5",
        type: "expense",
        amount: 230000,
        description: "Despesa fixa demo projetada",
        date: "2026-06-15",
        payment_method: "debit",
        is_projection: true,
        is_fixed: true,
        owners: [],
        tags: [],
        provenance: "projetado",
        line_items: [],
        due_date: null,
        installment_index: null,
        installment_total: null,
        has_refund_link: false,
      },
    ];

    const UPCOMING_BILLS = [
      {
        id: "t3",
        description: "Compromisso fixo demo",
        amount: 12500,
        due_date: "2026-06-28",
        is_projection: false,
      },
    ];

    const POCKETS = {
      liquid_cents: 842000,
      reserve_cents: 1500000,
      restricted_cents: 42000,
      illiquid_cents: 1200000,
      net_worth_cents: 3542000,
      accounts: [
        {
          id: "a1",
          name: "Conta demo principal",
          type: "bank",
          liquidity: "liquid",
          balance: 842000,
          institution: null,
        },
        {
          id: "a2",
          name: "Reserva demo",
          type: "savings",
          liquidity: "reserve",
          balance: 1500000,
          institution: null,
        },
        {
          id: "a3",
          name: "Benefício demo",
          type: "meal_voucher",
          liquidity: "restricted",
          balance: 42000,
          institution: null,
        },
        {
          id: "a4",
          name: "Ativo demo de longo prazo",
          type: "pension",
          liquidity: "illiquid",
          balance: 1200000,
          institution: null,
        },
      ],
    };

    const APP_INFO = {
      version: "0.1.0",
      db_path: "C:\\Users\\you\\AppData\\Roaming\\app.neko.finance\\neko-finance.db",
    };

    const ANNUAL = {
      year: 2026,
      months: Array.from({ length: 12 }, (_, i) => ({
        year: 2026,
        month: i + 1,
        income_cents: i + 1 === 6 ? 700000 : 0,
        performance_cents: i + 1 === 6 ? 450000 : 0,
        cost_of_living_cents: i + 1 === 6 ? 250000 : 0,
        fixed_out_cents: i + 1 === 6 ? 250000 : 0,
        daily_out_cents: 0,
        cartao_cents: 0,
        real_daily_avg_cents: 0,
        economia_cents: 0,
        patrimonio_cents: 0,
        savings_rate_bps: i + 1 === 6 ? 2200 : 0,
      })),
    };

    const TAG_TOTALS = [
      {
        id: "p",
        name: "! Pagar",
        color: "var(--brass-400)",
        emoji: null,
        is_special: true,
        total_cents: 2500,
      },
      {
        id: "v",
        name: "Categoria demo A",
        color: "var(--cat-sky)",
        emoji: null,
        is_special: false,
        total_cents: 10000,
      },
      {
        id: "d",
        name: "Categoria demo B",
        color: "var(--cat-coral)",
        emoji: null,
        is_special: false,
        total_cents: 35000,
      },
    ];

    const responses: Record<string, unknown> = {
      check_auth_status: "disconnected",
      get_dashboard_summary: SUMMARY,
      get_forecast: FORECAST,
      get_daily_budget_cmd: {
        per_day_cents: 4300,
        divisor_days: 30,
        categories: [
          { id: "cat-1", name: "Alimentação", amount_cents: 90000, position: 0 },
          { id: "cat-2", name: "Transporte", amount_cents: 39000, position: 1 },
        ],
      },
      get_ceiling_proposal_cmd: null,
      get_month_grid: FORECAST.daily.map((d) => ({
        date: d.date,
        day: Number(d.date.slice(8, 10)),
        income_cents: d.income_cents,
        fixed_out_cents: d.fixed_out_cents,
        daily_out_cents: d.daily_out_cents,
        balance_cents: d.balance_cents,
      })),
      tag_totals_for_month_cmd: TAG_TOTALS,
      list_tags_cmd: TAG_TOTALS,
      get_annual_metrics: ANNUAL,
      get_recent_transactions: TXNS,
      get_upcoming_bills_cmd: UPCOMING_BILLS,
      get_import_conflicts: [],
      create_transaction: "e2e-txn-id",
      get_app_info: APP_INFO,
      get_pockets: POCKETS,
      create_account: "e2e-account-id",
      list_cards: [],
      // Onboarding já concluído nestes cenários — o overlay não cobre o app.
      get_app_setting: "true",
      set_app_setting: null,
      ...ov,
    };

    Object.defineProperty(window, "__TAURI_INTERNALS__", {
      value: {
        invoke: (cmd: string) => {
          if (cmd in responses) return Promise.resolve(responses[cmd]);
          return Promise.reject(new Error(`e2e mock: unmocked command ${cmd}`));
        },
        transformCallback: () => 0,
      },
      configurable: true,
    });
  }, overrides);
}
